### ISSUE TITLE
Build guides not accounting for dependencies

### ISSUE THREAD

**Issue by dmindfuse** [solokeys/solo#384] opened 2020-02-25 15:11 UTC
I've had my solokey tap for several months now. Sadly I have barely used it. In fact it has been somewhat of a disappointing experience on many fronts.

1. No news on when solokeys support NFC on iOS. Your website remains elusive about a delivery date. 
2. Trying to upgrade to v3.1.0 from github has been unsuccessful and frustrating. Your manuals seem to be out of date, incomplete and incoherent. As a matter of fact, you're not providing full visibility of build dependencies. While i know this is difficult to do for so many platforms, at least covering Debian/Ubuntu would prove very helpful.

First things first, the python-solo won't install on debian/ubuntu. It fails on wheel for cryptography even though openssl-dev is installed. The error messages are pretty unhelpful in what to do about it.

Next, trying to "make firmware" fails as well. I tried this in a fresh ubuntu 18.04 VM, as well is in a physical mint installation. But I don't get far. 

My suggestion is to rewrite your documentation from the top, step by step for anyone who is new to solo and has absolutely no clue of what the dependencies are and how to resolve them when they appear. 

Hopefully I find some help here... dunno what else to do with the key but dispose of it.

**Comment by conorpp** [comment] 2020-02-25 15:28
AFAIK, for `solo-python`, you just need to run `pip3 install solo-python`.  Last I checked for Ubuntu, it was working fine.  If appears to stop working, please open and issue on the solo-python repo with specific details, and either Nicolas or myself will get to it.

I'm confused about the dependencies for the firmware.  There is only one you need to download, [ARM GCC](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads).  What is the missing dependency?  You can also use our Docker build.

iOS 13.3+ supports FIDO2 keys, to include SoloKeys.  There's a lot of news on this.

I'm closing this since it's not specific enough for us to act on.  We're very backlogged and can't address requests to rewrite everything.  Please re-open if you can be more specific and provide enough information to reproduce.  If you need customer support, you should contact SoloKeys.

**Closed by conorpp** 2020-02-25 15:28 UTC
