### ISSUE TITLE
Solokey and Keepass2

### ISSUE THREAD

**Issue by jolo1581** [solokeys/solo#261] opened 2019-08-08 05:34 UTC
Hi,

is it possible to use solokeys as a second factor in keepass like yubikey?

**Comment by youiopmop** [comment] 2019-08-09 03:56
duplicate of #208 and #218

**Comment by jolo1581** [comment] 2019-08-09 04:45
Sorry.
I have not found that posts. Thank you.
Then this issue can ne closed.

**Closed** 2019-08-09 04:45 UTC
